const p = document.querySelector('p');
const imgs = document.querySelectorAll('img');
const heading = document.querySelector('h2');
console.log(p);
console.log(heading);
console.log(heading.innerHTML);
console.log(heading.outerHTML);
const pizzaList = document.querySelector('.pizza');
console.log(pizzaList.textContent);
// pizzaList.textContent = `${pizzaList.textContent}🍕`;
pizzaList.insertAdjacentText('afterbegin', '🍕');
